import { db } from "./index";
import { products, Product } from "./schema";

export const initialProducts: Product[] = [
  {
    id: 13,
    slug: "greenvel-luxe-overflow-of-warmth",
    name: "GREENVEL LUXE",
    category: "Outerwear",
    price: 16500,
    currency: "BDT",
    color: "Emerald Green Suede Velvet",
    colorHex: "#16382c",
    description: "Crafted in Emerald green suede velvet, this jacket carries a calm richness that feels effortless. Hand-finished zardosi work lines the collar, adding depth without overpowering the design. The front zip with chain detailing brings a refined edge, while the button-loop strap at the cuff finishes the look with a practical, considered touch. Made for those who prefer quiet confidence over statement pieces. Warmth, naturally refined. Minimalism, worn with ease.",
    fabricDetails: "Emerald Green Suede Velvet with Hand-Finished Gold Zardosi Collar Embroidery. Front Zip with Chain Pull Detail & Button-Loop Cuff Straps. Silk-touch Cupro Lining.",
    fitInfo: "Refined architectural silhouette with quiet confidence. Structured collar and clean waistline drape.",
    origin: "Atelier Artisanal Studio, Bangladesh // O/W '25 Collection",
    sizes: ["XS", "S", "M", "L", "XL"],
    primaryImage: "/products/greenvel_luxe.jpg",
    secondaryImage: "/products/greenvel_luxe.jpg",
    campaignLook: "O/W '25 // LUXURY MINIMALISM",
    inStock: true,
    featured: true,
    badge: "OVERFLOW OF WARMTH '25",
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
  },
  {
    id: 14,
    slug: "mens-corduroy-utility-jacket",
    name: "MEN'S CORDUROY UTILITY JACKET",
    category: "Outerwear",
    price: 9800,
    currency: "BDT",
    color: "Midnight Obsidian Cord",
    colorHex: "#131b2e",
    description: "Architectural utility jacket tailored in heavy 8-wale tactile cotton corduroy. Features a relaxed camp-style spread collar, dual reinforced flap utility pockets with custom horn buttons, and contrast-direction ribbed cuff bands. Designed for functional versatility with quiet, structured elegance.",
    fabricDetails: "100% Heavyweight Tactile Cotton Corduroy (8-Wale). Custom Dyed Horn Buttons. Bemberg Cupro Inner Lining. Reinforced Double-Stitched Seams.",
    fitInfo: "Boxy relaxed tailoring with structured drop shoulders. Straight hem with side vent mobility.",
    origin: "Crafted in Dhaka Atelier, Bangladesh",
    sizes: ["S", "M", "L", "XL"],
    primaryImage: "/products/corduroy_utility_jacket_01.jpg",
    secondaryImage: "/products/corduroy_utility_jacket_02.jpg",
    campaignLook: "LOOK 11 // UTILITY EDIT",
    inStock: true,
    featured: true,
    badge: "NEW CAPSULE ARRIVAL",
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
  },
  {
    id: 1,
    slug: "oblique-oversized-overcoat",
    name: "OBLIQUE OVERSIZED OVERCOAT",
    category: "Outerwear",
    price: 14500,
    currency: "BDT",
    color: "Obsidian Noir",
    colorHex: "#0a0a0a",
    description: "Architectural double-breasted overcoat cut in heavyweight 640 GSM pure virgin wool gabardine. Engineered with exaggerated drop shoulders, hand-finished raw margins, and horn button closures.",
    fabricDetails: "100% Fine Virgin Wool (640 GSM). Cupro lining. Hand-cast horn hardware.",
    fitInfo: "Dramatic oversized silhouette. Intentionally exaggerated proportions.",
    origin: "Handcrafted in Dhaka Atelier, Bangladesh",
    sizes: ["XS", "S", "M", "L", "XL"],
    primaryImage: "/products/corduroy_utility_jacket_01.jpg",
    secondaryImage: "/products/corduroy_utility_jacket_02.jpg",
    campaignLook: "LOOK 01 // RUNWAY",
    inStock: true,
    featured: true,
    badge: "CAMPAIGN KEY LOOK",
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
  },
  {
    id: 2,
    slug: "monolith-sculpted-bomber",
    name: "MONOLITH SCULPTED BOMBER",
    category: "Outerwear",
    price: 8900,
    currency: "BDT",
    color: "Matte Black",
    colorHex: "#111111",
    description: "Cropped industrial bomber featuring high-density tactile flight nylon, heavy articulated sleeve pleats, matte silver industrial zip pull, and internal harness strap system.",
    fabricDetails: "High-density Cordura Nylon with DWR water-repellent coating. 100% Cotton jersey inner lining.",
    fitInfo: "Cropped body with elongated articulated sleeves.",
    origin: "Handcrafted in Dhaka Atelier, Bangladesh",
    sizes: ["S", "M", "L", "XL"],
    primaryImage: "/products/corduroy_utility_jacket_02.jpg",
    secondaryImage: "/products/corduroy_utility_jacket_03.jpg",
    campaignLook: "LOOK 02",
    inStock: true,
    featured: true,
    badge: "EDITION OF 75",
    createdAt: new Date("2026-01-02T00:00:00.000Z"),
  },
  {
    id: 3,
    slug: "deconstructed-raw-edge-blazer",
    name: "DECONSTRUCTED RAW BLAZER",
    category: "Tailoring",
    price: 9400,
    currency: "BDT",
    color: "Raw Obsidian",
    colorHex: "#161616",
    description: "Single-button deconstructed jacket with exposed canvas chest piece, unfinished lapel edges, and asymmetric vent detailing. Hand-basted contrast stitching throughout.",
    fabricDetails: "100% Fine Wool Crepe (380 GSM). Half-canvassed horsehair interlining.",
    fitInfo: "Structured shoulder with relaxed body drape.",
    origin: "Handcrafted in Dhaka Atelier, Bangladesh",
    sizes: ["XS", "S", "M", "L", "XL"],
    primaryImage: "/products/corduroy_utility_jacket_03.jpg",
    secondaryImage: "/products/greenvel_luxe.jpg",
    campaignLook: "LOOK 03",
    inStock: true,
    featured: true,
    badge: "ARCHITECTURAL EDIT",
    createdAt: new Date("2026-01-03T00:00:00.000Z"),
  },
  {
    id: 4,
    slug: "architectural-pleated-trousers",
    name: "ARCHITECTURAL WIDE TROUSERS",
    category: "Trousers",
    price: 4800,
    currency: "BDT",
    color: "Pitch Carbon",
    colorHex: "#1a1a1a",
    description: "High-rise tailored trousers constructed with dual inward deep front pleats, hidden elasticated waistband tab, and sweeping wide-leg puddle hem.",
    fabricDetails: "98% Tropical Virgin Wool, 2% Elastane. Corozo button closure.",
    fitInfo: "High-rise, ultra wide-leg silhouette with 34\" inseam puddle finish.",
    origin: "Crafted in Dhaka Atelier, Bangladesh",
    sizes: ["28", "30", "32", "34", "36"],
    primaryImage: "/products/greenvel_luxe.jpg",
    secondaryImage: "/products/corduroy_utility_jacket_01.jpg",
    campaignLook: "LOOK 04",
    inStock: true,
    featured: true,
    badge: "ESSENTIAL FORM",
    createdAt: new Date("2026-01-04T00:00:00.000Z"),
  },
  {
    id: 5,
    slug: "monolith-draped-hoodie",
    name: "MONOLITH DRAPED HOODIE",
    category: "Tops",
    price: 3800,
    currency: "BDT",
    color: "Obsidian Noir",
    colorHex: "#0f0f0f",
    description: "Ultra-heavyweight 620 GSM loopback cotton fleece sweatshirt featuring an exaggerated structured hood, concealed side seam pockets, and raw-rolled hems.",
    fabricDetails: "100% Organic GOTS Certified Combed Cotton (620 GSM). Pigment dyed and garment washed.",
    fitInfo: "Extreme boxy drop-shoulder cut.",
    origin: "Crafted in Dhaka Atelier, Bangladesh",
    sizes: ["XS", "S", "M", "L", "XL"],
    primaryImage: "/products/corduroy_utility_jacket_01.jpg",
    secondaryImage: "/products/corduroy_utility_jacket_02.jpg",
    campaignLook: "LOOK 05",
    inStock: true,
    featured: false,
    badge: "RESTOCKED",
    createdAt: new Date("2026-01-05T00:00:00.000Z"),
  },
  {
    id: 6,
    slug: "sculpted-shearling-trench",
    name: "SCULPTED CALFSKIN TRENCH",
    category: "Outerwear",
    price: 22500,
    currency: "BDT",
    color: "Aniline Black",
    colorHex: "#080808",
    description: "Floor-length trench coat rendered in buttery soft vegetable-tanned calfskin. Features dramatic storm flap, wide waist belt with matte oxidized buckle, and deep gusset pockets.",
    fabricDetails: "100% Full Grain Supple Calfskin. 100% Silk Twill lining.",
    fitInfo: "Oversized floor-grazing length.",
    origin: "Artisanal Atelier, Bangladesh",
    sizes: ["S", "M", "L"],
    primaryImage: "/products/corduroy_utility_jacket_02.jpg",
    secondaryImage: "/products/corduroy_utility_jacket_03.jpg",
    campaignLook: "LOOK 06 // ATELIER",
    inStock: true,
    featured: true,
    badge: "LIMITED ATELIER",
    createdAt: new Date("2026-01-06T00:00:00.000Z"),
  },
  {
    id: 7,
    slug: "concealed-placket-poplin-shirt",
    name: "CONCEALED POPLIN SHIRT",
    category: "Tops",
    price: 3200,
    currency: "BDT",
    color: "Optic Chalk",
    colorHex: "#f0f0f0",
    description: "Crisp 140/2 double-twist fine cotton poplin shirt. Concealed mother-of-pearl button placket, sharp angular collar, and extended double-button barrel cuffs.",
    fabricDetails: "100% Egyptian Cotton Poplin. Mother-of-pearl buttons.",
    fitInfo: "Slightly elongated tailored drape.",
    origin: "Crafted in Dhaka Atelier, Bangladesh",
    sizes: ["38", "39", "40", "41", "42"],
    primaryImage: "/products/corduroy_utility_jacket_03.jpg",
    secondaryImage: "/products/greenvel_luxe.jpg",
    campaignLook: "LOOK 07",
    inStock: true,
    featured: false,
    badge: "RUNWAY EDIT",
    createdAt: new Date("2026-01-07T00:00:00.000Z"),
  },
  {
    id: 8,
    slug: "kinetic-ribbed-turtleneck",
    name: "KINETIC RIBBED TURTLENECK",
    category: "Tops",
    price: 4500,
    currency: "BDT",
    color: "Pitch Carbon",
    colorHex: "#141414",
    description: "Fine 16-gauge seamless circular knit turtleneck crafted from superfine merino wool and cashmere blend. Engineered variable ribbing flatters body contour.",
    fabricDetails: "70% Superfine Merino Wool, 30% Cashmere blend.",
    fitInfo: "Skin-skimming architectural fit with extended thumbhole sleeves.",
    origin: "Crafted in Dhaka Atelier, Bangladesh",
    sizes: ["XS", "S", "M", "L", "XL"],
    primaryImage: "/products/greenvel_luxe.jpg",
    secondaryImage: "/products/corduroy_utility_jacket_01.jpg",
    campaignLook: "LOOK 08",
    inStock: true,
    featured: false,
    badge: "CORE SILHOUETTE",
    createdAt: new Date("2026-01-08T00:00:00.000Z"),
  },
  {
    id: 9,
    slug: "sculpted-monolith-derby",
    name: "SCULPTED MONOLITH DERBY",
    category: "Footwear",
    price: 7800,
    currency: "BDT",
    color: "Polished Black",
    colorHex: "#0c0c0c",
    description: "Chunky modernist derby shoe featuring an exaggerated squared toe, geometric welt line, and custom lightweight lug sole.",
    fabricDetails: "Polished Full Grain Box Calfskin. Goodyear welted construction. Heavy lug outsole.",
    fitInfo: "True to size. Fits bold and prominent.",
    origin: "Handcrafted in Dhaka Leather Atelier, Bangladesh",
    sizes: ["40", "41", "42", "43", "44", "45"],
    primaryImage: "/products/corduroy_utility_jacket_01.jpg",
    secondaryImage: "/products/corduroy_utility_jacket_02.jpg",
    campaignLook: "FOOTWEAR 01",
    inStock: true,
    featured: true,
    badge: "LIMITED RUN",
    createdAt: new Date("2026-01-09T00:00:00.000Z"),
  },
  {
    id: 10,
    slug: "modular-tactical-leather-tote",
    name: "MODULAR LEATHER TOTE 01",
    category: "Accessories",
    price: 5500,
    currency: "BDT",
    color: "Noir Carbon",
    colorHex: "#111111",
    description: "Architectural structured tote constructed from matte oiled saddle leather with magnetic fasteners, detachable cross-body industrial webbing harness, and padded 16\" laptop chamber.",
    fabricDetails: "Vegetable-tanned artisanal bridle leather. Magnetic hardware. Heavy metal zippers.",
    fitInfo: "Dimensions: 46cm x 38cm x 14cm.",
    origin: "Handcrafted in Dhaka Atelier, Bangladesh",
    sizes: ["ONE SIZE"],
    primaryImage: "/products/corduroy_utility_jacket_02.jpg",
    secondaryImage: "/products/corduroy_utility_jacket_03.jpg",
    campaignLook: "ACCESSORIES 01",
    inStock: true,
    featured: false,
    badge: "SIGNATURE ACCESSORY",
    createdAt: new Date("2026-01-10T00:00:00.000Z"),
  },
  {
    id: 11,
    slug: "asymmetric-tailored-vest",
    name: "ASYMMETRIC SCULPTED GILET",
    category: "Tailoring",
    price: 5800,
    currency: "BDT",
    color: "Obsidian Noir",
    colorHex: "#0e0e0e",
    description: "Sleeveless architectural vest with crossover asymmetric closure, structured peak lapel, and internal harness cinch. Wear layered or directly on skin.",
    fabricDetails: "Artisanal Fine Wool Twill (420 GSM). Cupro lining.",
    fitInfo: "Sharp tailored waist cinch.",
    origin: "Handcrafted in Dhaka Atelier, Bangladesh",
    sizes: ["XS", "S", "M", "L"],
    primaryImage: "/products/corduroy_utility_jacket_03.jpg",
    secondaryImage: "/products/greenvel_luxe.jpg",
    campaignLook: "LOOK 09",
    inStock: true,
    featured: false,
    badge: "RUNWAY",
    createdAt: new Date("2026-01-11T00:00:00.000Z"),
  },
  {
    id: 12,
    slug: "fluid-wool-overcoat-chalk",
    name: "FLUID GABARDINE COAT",
    category: "Outerwear",
    price: 13500,
    currency: "BDT",
    color: "Chalk Ash",
    colorHex: "#e2e2e2",
    description: "Statement unlined coat in contrasting alabaster chalk wool gabardine. Unstructured fluid silhouette with raglan sleeves and sweeping storm tab collar.",
    fabricDetails: "100% Pure Virgin Wool Gabardine. Natural horn buttons.",
    fitInfo: "Relaxed fluid silhouette.",
    origin: "Crafted in Dhaka Atelier, Bangladesh",
    sizes: ["S", "M", "L"],
    primaryImage: "/products/greenvel_luxe.jpg",
    secondaryImage: "/products/corduroy_utility_jacket_01.jpg",
    campaignLook: "LOOK 10 // FINALE",
    inStock: true,
    featured: true,
    badge: "COLLECTION FINALE",
    createdAt: new Date("2026-01-12T00:00:00.000Z"),
  },
];

export async function seed() {
  if (!process.env.DATABASE_URL) {
    console.log("No DATABASE_URL found. Running with in-memory product catalog.");
    return;
  }

  try {
    console.log("Seeding products into PostgreSQL database...");
    for (const item of initialProducts) {
      const { id, createdAt, ...insertData } = item;
      await db.insert(products).values(insertData).onConflictDoUpdate({
        target: products.slug,
        set: {
          name: item.name,
          price: item.price,
          description: item.description,
          fabricDetails: item.fabricDetails,
          fitInfo: item.fitInfo,
          primaryImage: item.primaryImage,
          secondaryImage: item.secondaryImage,
          badge: item.badge,
          featured: item.featured,
        },
      });
    }
    console.log("Products seeded successfully!");
  } catch (error) {
    console.warn("Could not seed database:", error);
  }
}
